spring:
    datasource:
        url: jdbc:mysql://54.226.94.88:3306/hsBank
        username: haresh
        password: 115488
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa.hibernate.ddl-auto: create-drop


